plugins {
    id 'java'
    id 'maven-publish'
}

group = 'net.YaRh'
version = '1.1'

repositories {
    mavenCentral()
}

dependencies {
    testImplementation platform('org.junit:junit-bom:6.0.0')
    testImplementation 'org.junit.jupiter:junit-jupiter'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}

test {
    useJUnitPlatform()
}

publishing {
    publications {
        mavenJava(MavenPublication) {
            from components.java
        }
    }

    repositories {
        maven {
            name = "GitHub"
            url = uri("https://maven.pkg.github.com/Yet-Another-Rabbit-Hole/CheapLog")

            credentials {
                username = System.getenv("USERNAME")
                password = System.getenv("TOKEN")
            }
        }
    }
}

tasks.register("update") {
    dependsOn testClasses
    dependsOn jar
    dependsOn javadoc
    dependsOn publishToMavenLocal
}